import tweeter
from gpt_2_tweet_generator import Gpt2Generator
from gru_tweet_generator import GruGenerator

import streamlit as st
import plotly

recent_tweet = '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The birth of artifcial intelligence starts today; I have the keys to dominance</p>&mdash; vivian-bot (@vivianbot1) <a href="https://twitter.com/vivianbot1/status/1327350048091418625?ref_src=twsrc%5Etfw">November 13, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>'
st.markdown(recent_tweet, unsafe_allow_html=True)

st.subheader('Last autogenerated Tweet: ')
st.markdown(recent_tweet, unsafe_allow_html=True)

# Setup for generators
ai = Gpt2Generator()
gru = GruGenerator()

st.subheader('Play around with how the twitter bot makes its tweets!')
st.subheader('GPT-2 Tweet Generator')
input_text = st.text_input('Type text or a prompt here', key='gpt2')

if input_text:
    temperature = st.slider('Creativity - Change how creative the text generator can be', 0.1, 5.0, 0.7)
    output = ai.twitter_respond(
        passing_input=input_text, 
        temperature=temperature)
    st.write(output[1])

st.subheader('GRU Tweet Generator')
input_text2 = st.text_input('Type text or a prompt here', key='gru')

if input_text2:
    vectorized_text = gru.vectorizer(input_text2)
    predicted_response = gru.generate(vectorized_text)
    predicted_words = gru.to_words(predicted_response * -1)
    st.write(" ".join(predicted_words[:50]))

